### ISSUE TITLE
Empty sync

### ISSUE THREAD

**Issue by JoskaM86** [Orange-OpenSource/keepass-vault-sync-plugin#4]
Sync creates empty group named according to keepass entry for vault and sysdate.

Is there a way how to find out, what's wrong in sync? Possibly it can be the format of value in the path field. I've used 

> \first_vault_node\

**Comment by osminm** [comment]
Having the same issue on a windows 10/keepass 2.47, empty group. The plugin menu option didn't show up when trying from a Mac/KeePassX 2.0.3 and hoped windows would work. Looked through the code and I can't see where the login URL is put together fully, e.g. https://localhost:8200/v1/auth/ldap/login/myusername.  Line 149 only shows of SynchronousVaultClient.cs shows "authPath + "/login/" + user sent to loginRequest. The function loginRequest doesn't show how this URL path is put together either "https://localhost:8200/v1/auth/l".

**Comment by Karreg** [comment]
Hello,

Unfortunately, KeePass is not friendly for displaying issues from a plugin. It's hard to say what's happening.
I'll try to work on this today.

**Comment by Karreg** [comment]
A new version has been released, with a log windows shown on synchronization to help understand what happens. Let me know if that helps.

**Comment by osminm** [comment]
The log window is helpful..it complains about missing Newtonsoft.Json. I see that dll in C:\Users\user\AppData\Local\KeePass\PluginCache\WnysolFW6S6layDubVWM but version is not what it doesn't match what it shows below.

Found vault entry vault-test
Exception for kv: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
   at Vault.VaultHttpClient.JsonSerialize[T](T content)
   at Vault.VaultHttpClient.Put[TI,TO](Uri uri, TI content, String vaultToken, TimeSpan wrapTtl, CancellationToken ct)
   at Vault.VaultClient.Put[TI,TO](String path, TI content, TimeSpan wrapTtl, CancellationToken ct)
   at Vault.Endpoints.Endpoint.Write[TParameters,TData](String path, TParameters data, CancellationToken ct)
   at VaultSyncPlugin.SynchronousVaultClient.<GetToken>d__e.MoveNext()
Secrets fetched, will now inject them in the database
Done.

**Comment by Karreg** [comment]
That's weird. The Newtonsoft JSON.NET dll should be included in the plgx file. There must be some mistmactch, and that may be related to my computer setup. I'll have a look at that.

**Comment by Karreg** [comment]
Found it. Vault.net requires JSON.NET 10 when I reference JSON.NET 12.
I'll try to bind the reference to use the latest JSON.NET version. If that causes issues, I will downgrade the JSON.NET version I use...

**Comment by Karreg** [comment]
Can you try with this version?

(Removed)

**Comment by Karreg** [comment]
Don't. it comes with some test code I left aside to manage JSON secrets... I'll give your another version soon :)

**Comment by Karreg** [comment]
Here is a version with JSON.NET 10 since keepass does not handle binding redirect. Tell me how it's going for you.

[VaultSyncPlugin.zip](https://github.com/Orange-OpenSource/keepass-vault-sync-plugin/files/6062838/VaultSyncPlugin.zip)

**Comment by osminm** [comment]
Looking better but seems I'm now dealing with a local issue..the process hangs after displaying a "Found vault entry.." message. I tested accessing the URL and noticed it launches fine from keepass with chrome & firefox, however it does not open with IE (2019 server ver 1809 via RDP). I'm on a Mac so will try spinning up a Windows 10 VM and test there instead.

**Comment by Karreg** [comment]
The plugin is not intended to work with keepassx. I'm not even sure it's working fine on linux with mono...

**Comment by osminm** [comment]
FYI, looks like I'm dealing with a TLS/IE issue since vault is behind a CA issued SSL cert. It showed this error:
Found vault entry vault-test
Exception for kv: One or more errors occurred.
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at VaultSyncPlugin.SynchronousVaultClient.<GetToken>d__e.MoveNext()
Secrets fetched, will now inject them in the database
Done.

I'm going to test next with a development vault non-ssl instance on my machine..expect that will work fine.

**Comment by Karreg** [comment]
It's hard to tell, this exception is an asynchronous exception, the real exception is hidden. I'll try to find where this is executed, and try to display the real exception instead.

**Comment by Karreg** [comment]
This should be an issue with authentication. There is not SSL validation since I have the same issue (see [here](https://github.com/Orange-OpenSource/keepass-vault-sync-plugin/blob/master/VaultSyncPlugin/SynchronousVaultClient.cs#L58))

Can you try with this version? I have added logs on authentication.

[VaultSyncPlugin.zip](https://github.com/Orange-OpenSource/keepass-vault-sync-plugin/files/6076943/VaultSyncPlugin.zip)

**Comment by osminm** [comment]
FYI, corrected the crypto issues in our config (it was affecting another tool). used the zip you shared above and getting to this point. Question, in your instructions you suggest using 'username' for basic auth. I used the name I gave the basic auth engine, defaults to userpass:
![image](https://user-images.githubusercontent.com/33492177/110979716-f9f33080-8332-11eb-80cc-b9fba582264b.png)


With SSL:
Found vault entry vault-test
Trying to authenticate to https://vault:8200//userpass/login/ with user xxx
Authenticated with token s.05Q28xxx...

Without SSL:
Found vault entry vault-test
Trying to authenticate to https://vault:8200//userpass/login/ with user xx
Authenticated with token s.05Q28VLxxx...
Found vault entry vault-test
Trying to authenticate to http://vault:8200//userpass/login/ with user xxx
Error on authentication: Unexpected response, status code BadRequest
   at Vault.VaultHttpClient.<HttpRequest>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Vault.VaultHttpClient.<HttpRequest>d__13`1.MoveNext()
Exception for kv: Unexpected response, status code BadRequest
   at Vault.VaultHttpClient.<HttpRequest>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Vault.VaultHttpClient.<HttpRequest>d__13`1.MoveNext()
Secrets fetched, will now inject them in the database
Done.

**Comment by Karreg** [comment]
OK, so there's an issue when vault is running without SSL. Is this something to fix? I'm not sure using vault in http is a good idea. Currently the plugin is disabling SSL check for self signed certificates, which is already a lowered security. I don't think I would decrease security more than that.

Also, I'm not even sure this is something I can fix in this plugin, it looks like it's more an issue of Vault.NET.

Let me know what you think about this.

**Comment by osminm** [comment]
FYI, we resolved SSL issues with cluster. I'm now able to connect, I see it gets a token but don't see any progress beyond that. There is probably 10 static secrets in the kv I'm trying to sync and I've waited over 20 minutes for the sync to complete but nothing. My setup / progress is in the attached picture.
![image](https://user-images.githubusercontent.com/33492177/117999977-67134a00-b313-11eb-9a9f-79349c23bfbf.png)

**Comment by Karreg** [comment]
The next step consists of fetching the secret list from your path:

```
Found vault entry vault-stuff
Trying to authenticate to https://vault:8200/ldap/login/ with user jojo
Authenticated with token s.7nPplksjdfjlkdjgHncswpnIHH5
6 keys fetched in stuff/
```

It looks like this is failing, without any exception. It could be a request not timed out.

However, it seems like `kv` is your root for all your secrets. The path defined in your entry is relative to this root. If I'm correct, looking for secrets in `kv/` will in fact create a request for `kv/kv/` on your vault.

You may try to target the path `/` but I don't think this is a good idea. You may better target a path in your root. For example if your root is `kv/` and have a sub-group called `stuff/`, your path will be `stuff` in your entry, and the related folder in vault will be `kv/stuff/`

About the use case, if you need to synchronize your whole vault in keepass, I may think that vault is not what you should use, and you should better used a shared keepass file...

**Comment by osminm** [comment]
FYI, changing path to a structure I know exists in the kv, e.g. tom, as you suggested gives a 'access forbidden' error. This is a very simple setup, the static engine mount point is "kv" and I have tom/ within it, among other test folders. Log output follows:

Found vault entry vault-test
Trying to authenticate to https://vault.com:8200//ldap/login/ with user xxxxxx
Authenticated with token s....xxxru
Access to tom forbidden
Secrets fetched, will now inject them in the database
Done.

**Comment by Karreg** [comment]
There's not much I can help on this issue. I guess you will find more information in your vault logs. Since authentication is working, the next steps are to configure vault. Have you tried using the vault API directly or the [vault CLI](https://www.vaultproject.io/docs/commands) to debug your issue?

**Comment by osminm** [comment]
Yes, these are all calls we've tested through postman, vault CLI, etc, and works fine there. e.g.:

Read secret:
curl --location --request GET 'https://secrets.com:8200/v1/kv/data/tom?version=2' \
--header 'X-Vault-Token: <removed>'
{"request_id":"removed","lease_id":"","renewable":false,"lease_duration":0,"data":{"data":{"test":"testng"},"metadata":{"created_time":"2020-08-07T21:15:12.136143Z","deletion_time":"","destroyed":false,"version":2}},"wrap_info":null,"warnings":null,"auth":null}

List secrets:
curl --location --request LIST 'https://secrets.com:8200/v1/kv/metadata' \
--header 'X-Vault-Token: <removed>'
{"request_id":"<removed>","lease_id":"","renewable":false,"lease_duration":0,"data":{"keys":["tom"]},"wrap_info":null,"warnings":null,"auth":null}

**Comment by et1875** [comment]
I'm not able to sync any data at all, looks like I'm able to login to vault but KeePass doesn't fetch any data from Vault even if i let it try sync for hours.
My config: 
![image](https://user-images.githubusercontent.com/71189839/139213833-3ebe5d71-0e2d-41e0-b48c-39f2bcc17477.png)

Vault URL:
![image](https://user-images.githubusercontent.com/71189839/139213567-30661f3c-7609-4630-acf1-40167a971040.png)
